% Created: 24.10.2012
% Last modified: 24.10.2012
% Version: 0.1
% Author: Ovidiu Pârvu
% 
% This program forces the peak of the ERKPP simulation trace generated by 
% the Hornberg 2005 signaling pathway model to be moved forward in time

function main

clc;
clear all;

% Start message
fprintf(1, 'Running the simulation...\n');

% Run the algorithm for finding the wanted peak
forceBehaviour;

% End message
fprintf(1, 'Done!\n');

end